services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  chat-app:
    build: .
    container_name: chat-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatdb
    command: ["node", "server.js"]  # Updated to use server.js
